- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
      
    - name: Check OS
      command: cat /etc/os-release
      register: os_info

    - name: Display OS
      debug:
        msg: "{{ os_info.stdout_lines }}"
        
    - name: Sleep 30 seconds
      command: sleep 30
